language: bash
services: docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - image="flyandi/ci-build-image-aws-lambda-node"
  - image="${image//'/'/-}"

script:
  - docker build -t "$image" "latest"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images